### ISSUE TITLE
It only says "standby service ready [verion.ch]

### ISSUE THREAD

**Issue by fantasaga** [Pexeus/LTE-Car#10]
It only says "standby service ready [verion.ch] and i cant see any video from the website on my laptop. Any help would be appreciated

**Comment by Pexeus** [comment]
You need to update your config.json file here: https://github.com/Pexeus/LTE-Car/blob/main/onboard/data/config.json

**Comment by fantasaga** [comment]
Update to the IP of my laptop or what

**Comment by fantasaga** [comment]
Tried my laptop IP, still doesnt work. BTW the rpi and the laptop are on the same network

**Comment by fantasaga** [comment]
Used the local IP of the laptop, now it says "connected" on the website but nothing shows up. I can also open up a terminal now

**Comment by Pexeus** [comment]
Now press start ;)

**Comment by fantasaga** [comment]
It says "Running" but still nothing shows up. Does this use raspicam? If it does i can try to use my Rpi 2. (its not supported on the new version of raspian)

**Comment by fantasaga** [comment]
![image](https://github.com/Pexeus/LTE-Car/assets/108121164/b367b439-c305-4f83-987f-21cdf09517a7)
Shows this error. Also i dont really need the GPIO, as i have a really good (crossfire) radio on my RC.

**Comment by fantasaga** [comment]
thanks for the quick support BTW :D

**Comment by fantasaga** [comment]
Perhaps you used the wrong cd, there is no Driver folder on my home. Maybe i can move all the files and make a new folder named Driver

**Comment by Pexeus** [comment]
> ![image](https://private-user-images.githubusercontent.com/108121164/305577090-b367b439-c305-4f83-987f-21cdf09517a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxMjU3MjEsIm5iZiI6MTcwODEyNTQyMSwicGF0aCI6Ii8xMDgxMjExNjQvMzA1NTc3MDkwLWIzNjdiNDM5LWMzMDUtNGY4My05ODdmLTIxY2RmMDk1MTdhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNlQyMzE3MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NzVjZDMyMjU0MGJmMWViNGVmN2IzZjk3ZTc0ZWZkYzg3NWRmZGI3NTczYWUwYmRiYjI5N2EzNzM2YzI4NTUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VEY3vE-eDR287jeOPnrSNFsGMc432qy5HRazxkuoioc) Shows this error. Also i dont really need the GPIO, as i have a really good (crossfire) radio on my RC.

cd into the onboard folder first, then run the program, its a realtive path

**Comment by fantasaga** [comment]
Ooh ok

**Comment by fantasaga** [comment]
![image](https://github.com/Pexeus/LTE-Car/assets/108121164/d310f0a8-aca9-4f8e-a033-98f8c60f433e)
Should i use a USB webcam now?

**Comment by fantasaga** [comment]
Also says "cant contact LTE antenna"

**Comment by fantasaga** [comment]
After running raspi-config and turning on legacy cam support, IT WORKSSSS! Thank you Pexeus for the help! Time for some adventures now

**Comment by fantasaga** [comment]
Ok now when i use the LTE dongle it says "offline" on the website. What IP should i use

**Comment by fantasaga** [comment]
I use my public ipv4 now, still doesnt work

**Comment by fantasaga** [comment]
How am i supposed to make this work with my LTE dongle. Perhaps a revers proxy tunnel ?

**Comment by fantasaga** [comment]
Ok this is going off topic, lemme close it. The "standby service" thingy already works by now, so ill make a new issue. Thanks for the quick support once again
