### ISSUE TITLE
Cannot use LTE dongle

### ISSUE THREAD

**Issue by fantasaga** [Pexeus/LTE-Car#11]
Works with local home WiFi, once i use the LTE dongle it doesnt work. Tried both public and local ip. LTE Dongle=Hilink e3372

**Comment by Pexeus** [comment]
you need to make several adjustments to your home networkto make this work, 
Tip: Just ask Chatgpt this: `how can i make it so i can reach a webserver on my home computer from anywhere in the world?`

Other option is to rent a cloud server, thats way easier to set up

**Comment by fantasaga** [comment]
Ok leme try

**Comment by fantasaga** [comment]
Can i use Zerotier?

**Comment by fantasaga** [comment]
Got it to work using zerotier, but the FPS on the website is like 8 to 20 and it only goes frame by frame. Can you make it so it always gets the latest frame, not all the frames.

**Comment by fantasaga** [comment]
After changing to a telecom provider that does not tthrottle upload speed (Before: 1mbps at like 1s latency on speedtest) OMG i went like through my whole neirborhood with almost no issues. Using 4G, Letency is like 200ms but OK. On speedtest i get 30mbps and 30ms latency, which is pretty good in Indonesia. And also using 90fps seems better on the dropped frames, rather than 30. Overall, its working greatly. If i get some good speedruns and chasing kids i will upload to YT. Thanks!!!!1111!!1!

**Comment by Pexeus** [comment]
so cool to hear that man! The latency is probably because the server you use is far away from where you live. I live in switzerland and used a server in Germany, thats why i got only about 30ms Latency. Make sure to send me the link to your youtube video!

**Comment by fantasaga** [comment]
ok bro!!!

**Comment by fantasaga** [comment]
Did my first run, Was like 80m or something. Still using my internal RC radio, bcs RSSI was still topping at 90-100 (im using 100mw)

**Comment by fantasaga** [comment]
Here lemme upload it. Im using runcam 2 for the HD recordding

**Comment by fantasaga** [comment]
Can i use the rpi on the rc car to record ?
