### ISSUE TITLE
Node-pty@0.10.1 install fails with ELIFECYCLE error on Raspberry Pi 4 Model B

### ISSUE THREAD

**Issue by UshnaGul** [Pexeus/LTE-Car#13]
I am trying to run this code on my raspberry pi but i am running into issues after running the 'npm i' command. Additional details are provided below:

Hardware: Raspberry Pi 4 Model B with 1.5GHz 64-bit quad-core ARMv8 CPU
Error log: 659 verbose pkgid node-pty@0.10.1
660 verbose cwd /home/SSXP-RAZ/Desktop/rccar/LTE-Car/onboard
661 verbose Linux 6.6.20+rpt-rpi-v8
662 verbose argv "/home/SSXP-RAZ/.nvm/versions/node/v14.21.3/bin/node" "/home/SSXP-RAZ/.nvm/versions/node/v14.21.3/bin/npm" "i"
663 verbose node v14.21.3 
664 verbose npm  v6.14.18
665 error code ELIFECYCLE
666 error errno 1
667 error node-pty@0.10.1 install: `node scripts/install.js`
667 error Exit status 1
668 error Failed at the node-pty@0.10.1 install script.
668 error This is probably not a problem with npm. There is likely additional logging output above.

**Comment by fantasaga** [comment]
What was the fix ?

**Comment by UshnaGul** [comment]
I upgraded to the following versions: npm -> 10.5.0
node js-> v21.7.1
I then had to delete the package-lock file  and clear cache to resolve the issue. 

P.S On later versions of raspberry pi, raspivid is replaced by libcamera-vid

**Comment by fantasaga** [comment]
I know
