### ISSUE TITLE
getaddrinfo enotfound

### ISSUE THREAD

**Issue by horusty** [Pexeus/LTE-Car#15]
Heya,

im running the newest version of PI OS debian 11,
ive got the pi connecting to the server. however when i hit start i get getaddrinfo enotfound.

any reccomendations? ive slightly altered the raspivid code to suit libcamera-vid but the rest it the same.

**Comment by horusty** [comment]
please ignore....I left in the [ ] *facepalm*

**Comment by Pexeus** [comment]
Pro gamer move
