### ISSUE TITLE
how to control ?

### ISSUE THREAD

**Issue by zoldaten** [Pexeus/LTE-Car#2]
hi!

1. could you tell please, which pins controls speed of the car?
i see in control.js:
const $towerX =  pin(17)
const $towerY = pin(27)
const $steer = pin(22)
const $esc = pin(18)
const $honk = pin(21)

as far as i understand 17,27,22 - for tower control. where forward-backward?

2. where server should be deployed ? if on PC how does raspberry will know the IP address of it ?
we are on 4G not wifi.

**Comment by Pexeus** [comment]
$esc

**Comment by zoldaten** [comment]
only one pin ?
i use motor driver like l298n.

**Comment by Pexeus** [comment]
yes, the ESC is connected and also controlled in the same way as a servo. you just nned to make sure that you are powering the motors externally. this page explains it quite well: https://www.instructables.com/Driving-an-ESCBrushless-Motor-Using-Raspberry-Pi/
