### ISSUE TITLE
Am I missing something ?

### ISSUE THREAD

**Issue by pinige** [Pexeus/LTE-Car#4]
In the video it says it will still work on the local network without an LTE dongle - Do I need to do something?

Onboard is a Pi 3B+

Onboard output:
Initiating stream
Initiating controls
Initiating telemetry (then after a while)
Cant contact LTE Antenna

Server is a Pi 4B

Server output:
receiving video stream from Onboard Pi
web page [ip address]:1300  - Status: Offline - start button doesn't do anything

I'm using a PS4 gamepad controller
Any help would be very much appreciated.
Thankyou.

**Comment by Pexeus** [comment]
Hey, sorry for the late response.

the LTE Antenna Error is no problem. this is just for getting some information from a specific type of LTE antenna. it should work over WLAN without issues. 

> did you check both the ports and the hosts in the config files?

if this is both correct, i assume the error is from something outside of the code. maybe the Raspberrys cannot reach eachother?

**Comment by pinige** [comment]
No problem - thanks for your help.
I will look further into the Raspberrys !
:-)
