### ISSUE TITLE
No video appears on the server website

### ISSUE THREAD

**Issue by fiveraptor** [Pexeus/LTE-Car#7]
Hello

I do not have a video on the website. The FPS and bitrate are displayed and updated continuously. The menu on the website says Status Offline and the terminal does not work either. I had to rewrite the onboard stream.js to the new libcamera-vid, because raspivid is no longer supported on the new versions of Raspberry Pi OS and the new V3 camera.

var` command = `libcamera-vid --width ${config.video.width} --height ${config.video.height} -t 0 --framerate ${fps} -b ${bitrate} --analoggain 1.0 --ev 0  -o - | socat - udp-sendto:${config.host}:${config.port_udp},shut-none`

Could it be that I have made a mistake?

Otherwise I simply entered the IP address of my server (in the internal network) and port 3000 in data/config.json. Have I done something wrong or have I forgotten something else that I need to configure?

Server nodejs v15.14.0
Pi nodejs v16.15.0 (the latest version that still supports pigpio)

**Comment by Pexeus** [comment]
Hi! I just took some time to fix all the Issues i could find. The program is split into the standby service and the code required to drive the car. I have updated the index.js file in /onboard to now start the standby service. After startup, press the start Button on the website to start the full process!

i havent worked with libcamera-vid yet so i cant help you with that. But make sure to try different browsers for the video to be displayed, since the decoder I used isnt really well supported

**Comment by pinige** [comment]
Hello fiveraptor
Have you had any success using libcamera-vid ?
If you have had success please could you share how you did it?

This works perfectly with raspivid and the older camera, so I thought I would try it with libcamera and a newer camera but have had no success so far.
Any information would be very helpful - thank you.

P.S. full respect to Pexeus - this is awesome !

**Comment by fantasaga** [comment]
I have been using libcamera-vid from the start, you just need to remove some of the parameters, and you need to change -w and -h to --width and --height.

**Comment by KevinUltimate123** [comment]
> I have been using libcamera-vid from the start, you just need to remove some of the parameters, and you need to change -w and -h to --width and --height.

How did you do this? can you explain further? because i've been looking everywhere for a solution and havent found one

I even tried downgrading to a buster raspberry pi os but that didnt work too

**Comment by fantasaga** [comment]
Command in onboard/stream.js (line 16): `libcamera-vid --width ${config.video.width} --height ${config.video.height} --timeout 0 --framerate ${fps} -o -`. That command is based on my memory, because the working working build SD card got missing somewhere.

**Comment by KevinUltimate123** [comment]
> Command in onboard/stream.js (line 16): `libcamera-vid --width ${config.video.width} --height ${config.video.height} --timeout 0 --framerate ${fps} -o -`. That command is based on my memory, because the working working build SD card got missing somewhere.

Yeah i tried that and still it hasn't worked. Im trying to edit the broadway.js decoder but that too hasn't worked. Is it possible for you to send me your code through gdrive fantasaga? and also what camera did you use?

**Comment by fantasaga** [comment]
i use random knockoff camera. And, you dont need to do anything to broadway.js, because i dont think it helps with your problem. Anyway, heres the gdrive

**Comment by fantasaga** [comment]
https://drive.google.com/file/d/1MSLHiehESxs1ORc2VGxBoymyl_T1rubR/view?usp=sharing

Replace stream.js with this file...

**Comment by jentevc** [comment]
> https://drive.google.com/file/d/1MSLHiehESxs1ORc2VGxBoymyl_T1rubR/view?usp=sharing
> 
> Replace stream.js with this file...

Thank you! You helped me so much. There was a problem with your conversion to google or something. At the end of "var command", the text cut off.

It has to end with: udp-sendto:${config.host}:${config.port_udp}`

**Comment by fantasaga** [comment]
Your welcome! Actually i didnt touch the rPi that runs this project in a
very long while, good to see people still getting success from my fix 😅😊
