### ISSUE TITLE
cant work out how to get further setting up

### ISSUE THREAD

**Issue by Keshin1988** [Pexeus/LTE-Car#8]
iv gotten to the point that i have my raspberry pi installed, and the server running on my pc. i can open the browser and see "new client connected: local
at this point i am still all on the same wifi.

on my raspberry pi however i keep getting errors like this

Node.js v18.19.0
rccar@rccar:~/onboard $ rccar@rccar:~ $ cd onboard
rccar@rccar:~/onboard $ sudo node index.js
UDP Connection Ready: [your host]:[udp port]
/home/rccar/onboard/index.js:13
        stream.init(udpClient, config)
                    ^

ReferenceError: udpClient is not defined
    at /home/rccar/onboard/index.js:13:21
    at events.connect (/home/rccar/onboard/node_modules/udplus/index.js:197:9)

i apologise in advance, im very basic at this coding, mostly copy and paste

**Comment by Pexeus** [comment]
Pull the changes, its fixed!

**Comment by Keshin1988** [comment]
i have run the new server file you uploaded, 
once i run it i get this 

```
rccar@rccar:~/onboard $ npm i

up to date, audited 29 packages in 5s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
rccar@rccar:~/onboard $ node index.js
standby service ready [verion.ch]
```

i still have no connection between the two. no doubt i have done something wrong or havent changed something.

**Comment by Pexeus** [comment]
reclone the repo. on bot ur server and RC car. when everything is running, you need to hit the "start" button on the sidebar of the webinterface

**Comment by Keshin1988** [comment]
hey there i have recloned the repo on both server and rc car. below is what i get 

Raspberry pi onboard......................
![onboard](https://github.com/Pexeus/LTE-Car/assets/114125729/5ec8b9df-b0c1-4bba-a3ce-dd7b980b17a2)

Windows pc Server......
![Server](https://github.com/Pexeus/LTE-Car/assets/114125729/139f2f8d-eef7-4ec3-acd3-64f565c2212b)

Clicking start in the browser doesnt do anything, i also get no connection in terminal

**Comment by Keshin1988** [comment]
ok started completely fresh and this is where i get stuck, as you can see in the screenshot below the server and browser communicate fine. however you can see the onboard (rasbpberry pi) wont connect at all. it just displays "standby service ready [verion.ch]"   clicking start or terminal in browser have no affect on anything

Everything is on the same network/wifi and i can ssh in as seen
                                                 
![help](https://github.com/Pexeus/LTE-Car/assets/114125729/ed9e90cd-f94d-406e-ab0c-78c841a99a0a)
