### ISSUE TITLE
steers right when i steer left

### ISSUE THREAD

**Issue by Keshin1988** [Pexeus/LTE-Car#9]
Can you please show me or explain how to invert the steering servo. my servo steers opposite to what i steer on the gamepad controller.

EXTRA:   
is there a way to get this to work with a webcam instead of the raspberrypi camera? i just get an error saying no camera when i connect the webcam (with the rpi camera disconnected) however i can see the webcam is being found on the usb.

**Comment by Pexeus** [comment]
For the steering, i already implemented this, just switch the "reverse" variable :)
![image](https://github.com/Pexeus/LTE-Car/assets/64081121/c8bd7f08-7155-4baa-98f1-1cc257da5c1e)

for the different webcam: Definetly doable, but u will have to modify the code

**Comment by Keshin1988** [comment]
Awesome thank you. I'm so close to it all working. I can drive on wifi now. Next is to get it working on the 4g... 

I wish I knew how to code that in I very basically understand some of code I read. I'll have to learn it.

**Comment by Keshin1988** [comment]
thank you that worked, before i close this topic is it possible to use my Logitech steering wheel and pedals with this? what setting would i change please

second thing, can you tell me what settings i need to change to run over 4g, i have a 4g usb. im just unsure which settings need changing to make it connect over 4g, 

currently wifi control is working but i need 4g

**Comment by Pexeus** [comment]
the gamepad is 99% doable, just check this out: https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API/Using_the_Gamepad_API

and then implement it here: server/client/src/control

For the 4G you ned a Cloudserver, im sure ull find the rest out urself ;)
